[package]
name = "mikrotik"
version = "0.0.1"
edition = "2021"

[dependencies]
base64 = "0.13.0"
color-eyre = "0.6.1"
futures = "0.3.17"
reqwest = { version = "0.11.4", features = ["rustls-tls", "serde_json", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_derive = "1.0.136"
serde_json = "1.0.68"
tokio = { version = "1.10.1", features = ["full"] }
tokio-test = "0.4.2"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
